select *
from gold.dim_customers;
select *
from gold.dim_products;
select *
from gold.fact_sales;
---Find total products by category

Select category,
count(product_key) As total_products
from gold.dim_products
where category is not null
group by category
order by total_products DESC;
--///Magnitude Analysis? Find the Total Number customers by countries///
---find total customers by coutries
Select country,
count(customer_key) As total_customers
from gold.dim_customers
group by country
order by total_customers DESC

--- Find total coustomers by gender
Select gender,
count(customer_key) As total_customers
from gold.dim_customers
group by gender
order by total_customers DESC
---Find total products by category

Select category,
count(product_key) As total_products
from gold.dim_products
where category is not null
group by category
order by total_products DESC;

---what is the average cost in each category

Select category,
Avg(cost)As avg_cost
from gold.dim_products
group by category
order by avg_cost DESC;
---What is the total revenue generated for each category?

Select p.category,
sum(f.sales_amount) as total_revenue
from gold.fact_sales f
left join gold.dim_products p
on p.product_key= f.product_key
group by p.category
order by total_revenue DESC;

select * from gold.dim_products;

select * from gold.fact_sales;

---what is the total revenue generated by each customer?
select 
c.customer_key,
c.first_name,
c.last_name,
sum(f.sales_amount) AS total_revenue
from gold.fact_sales f
left join gold.dim_customers c
ON c.customer_key=f.customer_key
group by
c.customer_key,
c.first_name,
c.last_name
Order by total_revenue desc


---Change- over time
--- Analyze sales performance over Time
select 
year(order_date) as order_year,
sum(sales_amount) as total_sales,
COUNT(DISTINCT customer_key) as total_customers,
sum(quantity) as total_quantity
from gold.fact_sales
where order_date is not null
group by year(order_date)
order by year(order_date);

---
select 
year(order_date) as order_year,
month(order_date) as order_month,
sum(sales_amount) as total_sales,
COUNT(DISTINCT customer_key) as total_customers,
sum(quantity) as total_quantity
from gold.fact_sales
where order_date is not null
group by year(order_date),month(order_date)
order by year(order_date),month(order_date);
-- date using datetrunc
select 
datetrunc(year, order_date) as order_date,
sum(sales_amount) as total_sales,
COUNT(DISTINCT customer_key) as total_customers,
sum(quantity) as total_quantity
from gold.fact_sales
where order_date is not null
group by datetrunc(year, order_date)
order by datetrunc(year, order_date);

--- date using format

select 
FORMAT(order_date, 'yyyy-MMM') as order_date,
sum(sales_amount) as total_sales,
COUNT(DISTINCT customer_key) as total_customers,
sum(quantity) as total_quantity
from gold.fact_sales
where order_date is not null
group by FORMAT(order_date, 'yyyy-MMM')
order by FORMAT(order_date, 'yyyy-MMM');

----Cumulative Analysis
----Calculate the total sales per month and the running total total of sales over time
select
order_date,
total_sales,
sum(total_sales) over (Partition by order_date order by order_date) as running_total_sales
from
(
select
DATETRUNC(month, order_date) AS order_date,
sum(sales_amount) as total_sales
from gold.fact_sales
where order_date is not null
group by DATETRUNC(month, order_date)
)t
---order by DATETRUNC(month, order_date)

select
order_date,
total_sales,
---window function
sum(total_sales) over (Partition by order_date order by order_date) as running_total_sales,
AVG(avg_price) over (order by order_date) as moving_average_price
from
(
select
DATETRUNC(year, order_date) AS order_date,
sum(sales_amount) as total_sales,
AVG(price) AS avg_price
from gold.fact_sales
where order_date is not null
group by DATETRUNC(year, order_date)
)t

---Performance Analysis
---Analyze the yearly performance of products by comparing
---each product's sales to both its average sales performance and the previous year's sales.
WITH yearly_product_sales AS (
SELECT
YEAR(f.order_date) AS order_year,
p.product_name,
SUM(f.sales_amount) AS current_sales
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON f.product_key = p.product_key
where f.order_date IS NOT NULL
GROUP BY
YEAR(f.order_date),
p.product_name
)
select
order_year,
product_name,
current_sales,
AVG(current_sales) over (PARTITION BY product_name) AS avg_sales,
current_sales - AVG(current_sales) over (PARTITION BY product_name) AS diff_avg,
CASE WHEN current_sales - AVG(current_sales) over (PARTITION BY product_name) > 0 THEN 'Above avg'
     WHEN current_sales - AVG(current_sales) over (PARTITION BY product_name) < 0 THEN 'Below Avg'
     ELSE 'Avg'
END avg_change,
LAG(current_sales) OVER (PARTITION by product_name order by order_year) py_sales
from yearly_product_sales
order by product_name, order_year;
--- Advance Analystics project Part-to-whole Proportional
--- Analyze how an individual part is performing compared toihe overall,allowing us to understand which category has the greatest imapct on business.
--- which categories contributr the most to overall sales?

Select category,
SUM(sales_amount) total_sales
from gold.fact_sales f
left join gold.dim_products p
ON p.product_key = f.product_key
group by category

select 
category,
SUM(sales_amount) as total_sales,
---Sum(total_sales) Over() overall_sales
CONCAT(round((cast( sales_amount as Float) / Sum(sales_amount) over ())*100,2),'%') as percentage_of_total

from gold.fact_sales f
left join gold.dim_products p
ON p.product_key = f.product_key
group by category
---from gold.fact_sales
order by total_sales DESC;


